public class basicExample {

	 public integer aa = 40; //global variable non static 

    
    public static void myMethod(){
        
        Integer a = 10; //variable  initalization and declaration
        
        System.debug(a); // 10
        
        a=20;  // initalization again
        
        system.debug(a); // 20 

        Final Integer b; //declartion
        
      
        
    
        
        b = 40;  // initalization

         System.debug(b);
        
    }
    
    public static void datatyp(){
        
        integer a=2147483647;
        
       integer b = a +1 ;
        system.debug(b);
        
        long d = 2147483647;
        
        long m = d + 2 ;
        
        system.debug(m);
        
        
        boolean isbool = true;
        
        system.debug(isbool);
        
        String myid = 'a00IS000004WuGWYA0kdljsaflka';
        
     
        
        system.debug(myid);
        
        
        
        
    }
    
  
    
  

}