public class dateExample {
    
    public static void myMethod(){
        
        Date dt = Date.newInstance(2024,01,04);
        
        system.debug(dt.year()); //2024 non-static
        
        system.debug(date.today()); //static
        //time
        
        Time tt = time.newInstance(1,60,20,33);
        
        system.debug(tt.hour());
        
        //decimal
        //
        double deci = 20.33;
        
        system.debug(deci);
        
        
        
    }

}